name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  logic-test:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:11.6.0-runtime-ubuntu20.04
      options: --privileged  # Enable privileged mode to access GPU features

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64

    - name: Install miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda
        /opt/miniconda/bin/conda init
        exec bash
        conda create -n pycudae
        conda activate pycudae
        conda install cudatoolkit=12.0 -c pytorch

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies

    - name: Run tests
      run: |
        python -m pytest
