name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  logic-test:
    runs-on: ubuntu-latest

    container:
      image: continuumio/miniconda3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        conda install python=3.10

    - name: Install PyCUDA and Dependencies
      run: |
        conda install -c conda-forge pycuda

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest
