name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  logic-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64
    
    - name: Install Nvidia Driver
      run: |
        sudo apt update
        sudo apt install ubuntu-drivers-common
        sudo ubuntu-drivers install
        nvidia-smi

    - name: Install Pycuda
      run: |
        sudo apt update
        sudo apt install python3-pycuda
    
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest